### ISSUE TITLE
import時にエラー"illegal type for path parameter"が出る

### ISSUE THREAD

**Issue by elnikkis** [uehara1414/japanize-matplotlib#3]
# 問題

import時に次のようなエラーが出ます。

```
Traceback (most recent call last):
  File "test_japanize_matplotlib.py", line 6, in <module>
    import japanize_matplotlib
  File "[...]/japanize-matplotlib/japanize_matplotlib/__init__.py", line 12, in <module>
    font_files = font_manager.findSystemFonts(fontpaths=font_dirs)
  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 343, in findSystemFonts
    files = list_fonts(path, fontexts)
  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 179, in list_fonts
    return cbook.listFiles(directory, pattern)
  File "/usr/lib/python3/dist-packages/matplotlib/cbook.py", line 1178, in listFiles
    for dirname, dirs, files in os.walk(root):
  File "/usr/lib/python3.5/os.py", line 371, in walk
    scandir_it = scandir(top)
TypeError: scandir: illegal type for path parameter
```

pathlibが使えない関数が呼ばれていることが原因のようです。

# 環境

- japanize-matplotlib (1.0.4)
- matplotlib (2.0.0)
- Python 3.5.3
- WSL上のDebian 9.9

**Comment by uehara1414** [comment]
@elnikkis 報告・修正ありがとうございます！
手元で動作確認出来次第取り込みますね

**Comment by elnikkis** [comment]
マージありがとうございました！
